### ISSUE TITLE
Lifehack index

### ISSUE THREAD

**Issue by veneziacarl** [veneziacarl/lifehacks_review#3]
As a User
I want to view a list of all lifehacks
So I can learn from others
- [x] I should see an index of all lifehacks at the root of the app
- [x] I should see a list sorted by date by default
- [x] I must be able to sort by rating
- [x] I must be able to sort by date
- [x] I must be able to sort by category
- [x] I should see the title, creator, date, average rating of the lifehack

**Comment by Tko176** [comment]
FYI This was erroneously labeled as Resolve 3 and Resolve 5 in gitub.
